#!groovy

@Library('jenkins-common-lib') _

node('master') { timestamps
{
    stage('前提条件')
    {
        def env = loadEnvConfig()
    }

    /**  UT試験
     *  試験条件：コマンド結果に標準エラーが含まれていないこと。
     *  期待する動作：結果がOKとなること。
     */
    stage('test-case-1')
    {
        try
        {
            result = sshCmd(env, 'webap', 'ls /opt/app/lib')

            printMsg('info', result['stdout'])

            assert result['stderror'] == null
        }
        catch(Exception e) {

            println 'result: NG'
        }

        println 'result: OK'
    }

    /**  UT試験
      *  試験条件：コマンド結果に標準エラーが含まれていること。
      *  期待する動作：結果がNGとなること。
      */
    stage('test-case-2')
    {
        try
        {
            result = sshCmd(env, 'webap', 'ls /opt/app/libbb')

            printMsg('info', result['stderror'])

            assert result['stderror'] == null
        }
        catch(Exception e) {

            println 'result: NG'
        }

        println 'result: OK'
    }
}}
