#!/usr/bin/groovy

@Library('jenkins-common-lib') _

stage('test-notificationJobHistory') { timestamps
{
    node('master')
    {
        // 通知タイトル
        //manager.build.setDisplayName('#' + manager.build.number + " " + currentBuild.result)
        manager.build.setDisplayName('#' + manager.build.number + " " + 'SCUSESS')

        // 終了時間を追加
        end_time = new Date().dateTimeString
        manager.addShortText("undeployed: $end_time", "grey", "white", "0px", "white")
        manager.createSummary("gear2.gif").appendText("<h2>Undeployed: $end_time</h2>", false, false, false, "grey")

        // 成果物の保存
        //manager.build.keepLog(true)
    }
}}
