#!groovy

@Library('jenkins-common-lib') _

node('master') { timestamps
{
    /**  UT試験
     *  期待する動作：
     */
    stage('test-case-1')
    {
        try
        {

        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }

    /**  UT試験
      *  期待する動作：
      */
    stage('test-case-2')
    {
        try
        {

        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }
}}
