#!groovy

@Library('jenkins-common-lib') _

node('master') { timestamps
{
    /**  UT試験
     *  期待する動作：設定をハッシュ値形式で取得できること。
     */
    stage('test-case-1')
    {
        try
        {
            def env = loadEnvConfig()

            println 'env.mail.address.debug:' + env.mail.address.debug
            println 'env.setting.ssh.timeoutSec: ' + env.setting.ssh.timeoutSec
            println 'env.session.ssh.webap.identity: ' + env.session.ssh.webap.identity
            println 'env.resource.monitor.wu.execute.faital.keyword: ' + env.resource.monitor.wu.execute.faital.keyword
            println 'env.size(): ' + env.size()
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }

    /**  UT試験
      *  期待する動作：変数を代入したパラメータで取得できること。
      */
    stage('test-case-2')
    {
        try
        {
            def env = loadEnvConfig()

            def server = 'batch'
            println 'env.session.ssh."${server}".identity: ' + env.session.ssh."${server}".identity
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }
}}
